/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Saved Datasets */
        get: operations["list_saved_datasets_api_v1_datasets_get"];
        put?: never;
        /** Create Saved Dataset */
        post: operations["create_saved_dataset_api_v1_datasets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/examples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Datasets Examples */
        get: operations["datasets_examples_api_v1_datasets_examples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/inspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Datasets Inspect */
        post: operations["datasets_inspect_api_v1_datasets_inspect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Datasets Preview */
        post: operations["datasets_preview_api_v1_datasets_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/estimators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estimators */
        get: operations["estimators_api_v1_estimators_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Experiments */
        get: operations["list_experiments_api_v1_experiments_get"];
        put?: never;
        /** Create Experiment */
        post: operations["create_experiment_api_v1_experiments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{experiment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Experiment */
        get: operations["get_experiment_api_v1_experiments__experiment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{experiment_id}/result-layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Result Layout */
        put: operations["save_result_layout_api_v1_experiments__experiment_id__result_layout_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/{experiment_id}/tournament": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Tournament */
        post: operations["create_tournament_api_v1_experiments__experiment_id__tournament_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Run */
        post: operations["validate_run_api_v1_runs_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis */
        get: operations["get_analysis_api_v1_runs__run_id__analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifacts */
        get: operations["get_artifacts_api_v1_runs__run_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_api_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Events */
        get: operations["stream_events_api_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/exports/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Run */
        get: operations["export_run_api_v1_runs__run_id__exports__kind__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/feature-importance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calculate Feature Importance */
        post: operations["calculate_feature_importance_api_v1_runs__run_id__feature_importance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History */
        get: operations["get_history_api_v1_runs__run_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Predictions */
        get: operations["get_predictions_api_v1_runs__run_id__predictions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Result */
        get: operations["get_result_api_v1_runs__run_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Run */
        post: operations["retry_run_api_v1_runs__run_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflow/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Workflow */
        post: operations["validate_workflow_api_v1_workflow_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisResponse */
        AnalysisResponse: {
            dataset?: components["schemas"]["DatasetPreviewResponse"] | null;
            feature_importance: components["schemas"]["ImportanceResponse"];
            /**
             * Metric
             * @enum {string}
             */
            metric: "rmse" | "mae" | "r2" | "accuracy" | "roc_auc" | "pr_auc" | "log_loss" | "f1_macro";
            /**
             * Task
             * @enum {string}
             */
            task: "regression" | "binary_classification" | "multiclass_classification";
            test?: components["schemas"]["AnalysisSplitResponse"] | null;
            train: components["schemas"]["AnalysisSplitResponse"];
            validation: components["schemas"]["AnalysisSplitResponse"];
        };
        /** AnalysisSplitResponse */
        AnalysisSplitResponse: {
            confusion_matrix?: components["schemas"]["ConfusionResponse"] | null;
            /** Cost */
            cost?: number | null;
            cross_validation?: components["schemas"]["CrossValidationResponse"] | null;
            /** Decision Threshold */
            decision_threshold?: number | null;
            /** Metrics */
            metrics: {
                [key: string]: number | null;
            };
            multiclass_roc?: components["schemas"]["MulticlassRocResponse"] | null;
            /** Per Class */
            per_class?: {
                [key: string]: string | number | null;
            }[] | null;
            /** Positive Label */
            positive_label?: string | null;
            precision_recall_curve?: components["schemas"]["PrecisionRecallResponse"] | null;
            regression_diagnostics?: components["schemas"]["RegressionDiagnostics"] | null;
            roc_curve?: components["schemas"]["RocResponse"] | null;
            /** Selected Metric */
            selected_metric?: ("rmse" | "mae" | "r2" | "accuracy" | "roc_auc" | "pr_auc" | "log_loss" | "f1_macro") | null;
            /** Threshold Diagnostics */
            threshold_diagnostics?: {
                [key: string]: number | null;
            }[] | null;
            /** Value */
            value?: number | null;
        };
        /** ArtifactResponse */
        ArtifactResponse: {
            /** Events */
            events: components["schemas"]["RunEventResponse"][];
            experiment: components["schemas"]["ExperimentResponse"];
            run: components["schemas"]["RunResponse"];
        };
        /** AttemptResponse */
        AttemptResponse: {
            /** Attempt Id */
            attempt_id: string;
            /** Created At */
            created_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Heartbeat At */
            heartbeat_at?: string | null;
            /** Parent Run Id */
            parent_run_id?: string | null;
            /** Run Id */
            run_id: string;
            /** Service Id */
            service_id?: string | null;
            /** Started At */
            started_at?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "completed" | "failed" | "cancelled" | "interrupted";
            /** Termination Reason */
            termination_reason?: ("timeout" | "cancelled" | "interrupted") | null;
            /**
             * Termination Requested
             * @default false
             */
            termination_requested: boolean;
            /** Timeout Seconds */
            timeout_seconds?: number | null;
            /** Worker Created At */
            worker_created_at?: number | null;
            /** Worker Pid */
            worker_pid?: number | null;
        };
        /** BestResponse */
        BestResponse: {
            /** Best Cost */
            best_cost?: number | null;
            /** Best Metric */
            best_metric?: number | null;
            /** Best Params */
            best_params?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
        };
        /** CapabilitiesResponse */
        CapabilitiesResponse: {
            /** Epoch Progress */
            epoch_progress: boolean;
            /** Feature Importance */
            feature_importance: string | null;
            /** Permutation Importance */
            permutation_importance: boolean;
            /** Probability Output */
            probability_output: boolean;
            /** Scaling Recommended */
            scaling_recommended: boolean;
        };
        /** ChoiceSearchParam */
        ChoiceSearchParam: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "choice";
            /** Values */
            values: (string | number | boolean)[];
        };
        /** ColumnResponse */
        ColumnResponse: {
            /** Dtype */
            dtype: string;
            /** Examples */
            examples?: components["schemas"]["JsonValue"][];
            /** Missing */
            missing: number;
            /** Name */
            name: string;
            /** Unique */
            unique: number;
        };
        /** ConfusionResponse */
        ConfusionResponse: {
            /** False Negative */
            false_negative?: number | null;
            /** False Positive */
            false_positive?: number | null;
            /** Labels */
            labels: string[];
            /** True Negative */
            true_negative?: number | null;
            /** True Positive */
            true_positive?: number | null;
            /** Values */
            values: number[][];
        };
        /** CrossValidationResponse */
        CrossValidationResponse: {
            /** Folds */
            folds: components["schemas"]["FoldResponse"][];
            /** Mean */
            mean: number;
            /** Standard Deviation */
            standard_deviation: number | null;
        };
        /** CsvPreviewRequest */
        CsvPreviewRequest: {
            /** Csv Text */
            csv_text: string;
        };
        /** DatasetCreateRequest */
        DatasetCreateRequest: {
            /** Csv Text */
            csv_text: string;
            /** Name */
            name: string;
        };
        /** DatasetInspectRequest */
        DatasetInspectRequest: {
            /** Csv Text */
            csv_text?: string | null;
            /** Dataset Id */
            dataset_id?: string | null;
            evaluation?: components["schemas"]["EvaluationSpec"] | null;
            /**
             * Name
             * @default breast_cancer
             */
            name: string | null;
            /**
             * Source
             * @default example
             * @enum {string}
             */
            source: "example" | "csv" | "stored";
            split?: components["schemas"]["SplitSpec"];
            /**
             * Target Column
             * @default target
             */
            target_column: string;
            /**
             * Task
             * @default binary_classification
             * @enum {string}
             */
            task: "regression" | "binary_classification" | "multiclass_classification";
        };
        /** DatasetPreviewResponse */
        DatasetPreviewResponse: {
            /** Columns */
            columns: components["schemas"]["ColumnResponse"][];
            /** Numeric Summary */
            numeric_summary: components["schemas"]["NumericSummaryResponse"][];
            /** Preview */
            preview: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /** Row Count */
            row_count: number;
            split_summary?: components["schemas"]["SplitResponse"] | null;
            summary: components["schemas"]["TableSummaryResponse"];
            /** Target Candidates */
            target_candidates: string[];
            target_summary?: components["schemas"]["TargetResponse"] | null;
        };
        /** DatasetSpec */
        DatasetSpec: {
            /** Csv Text */
            csv_text?: string | null;
            /** Dataset Id */
            dataset_id?: string | null;
            /**
             * Name
             * @default breast_cancer
             */
            name: string | null;
            /**
             * Source
             * @default example
             * @enum {string}
             */
            source: "example" | "csv" | "stored";
            /**
             * Target Column
             * @default target
             */
            target_column: string;
        };
        /** DependencyResponse */
        DependencyResponse: {
            /** Install */
            install: string | null;
            /** Installed */
            installed: boolean;
            /** Required */
            required: string | null;
        };
        /** DistributionRow */
        DistributionRow: {
            /** Count */
            count: number;
            /** Label */
            label: string | number | boolean;
            /** Percentage */
            percentage: number;
        };
        /** EstimatorDefaults */
        EstimatorDefaults: {
            /** Allowed Params */
            allowed_params: string[];
            /** Fixed Params */
            fixed_params: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Search Space */
            search_space: {
                [key: string]: components["schemas"]["ChoiceSearchParam"] | components["schemas"]["IntSearchParam"] | components["schemas"]["FloatSearchParam"];
            };
        };
        /** EstimatorResponse */
        EstimatorResponse: {
            capabilities: components["schemas"]["CapabilitiesResponse"];
            /** Defaults */
            defaults: {
                [key: string]: components["schemas"]["EstimatorDefaults"];
            };
            dependency: components["schemas"]["DependencyResponse"];
            /** Description */
            description: string;
            /** Group */
            group: string;
            /** Install */
            install?: string | null;
            /** Label */
            label: string;
            /** Optional Dependency */
            optional_dependency: string | null;
            /** Tasks */
            tasks: ("regression" | "binary_classification" | "multiclass_classification")[];
        };
        /**
         * EvaluationSpec
         * @description Scientifically reproducible candidate evaluation settings.
         */
        EvaluationSpec: {
            /**
             * Decision Threshold
             * @default 0.5
             */
            decision_threshold: number;
            /**
             * Folds
             * @default 5
             */
            folds: number;
            /** Positive Label */
            positive_label?: string | number | boolean | null;
            /**
             * Protocol
             * @default holdout
             * @enum {string}
             */
            protocol: "holdout" | "cross_validation";
            /** Random State */
            random_state?: number | null;
            /**
             * Refit Best
             * @default true
             */
            refit_best: boolean;
            /**
             * Shuffle
             * @default true
             */
            shuffle: boolean;
            /** Stratify */
            stratify?: boolean | null;
            /** Test Size */
            test_size?: number | null;
        };
        /** ExampleDatasetResponse */
        ExampleDatasetResponse: {
            /**
             * Default Metric
             * @enum {string}
             */
            default_metric: "rmse" | "mae" | "r2" | "accuracy" | "roc_auc" | "pr_auc" | "log_loss" | "f1_macro";
            /** Description */
            description: string;
            /** Features */
            features: number;
            /** Label */
            label: string;
            /** License */
            license: string;
            /** License Url */
            license_url: string;
            /** Name */
            name: string;
            /** Rows */
            rows: number;
            /** Source */
            source: string;
            /** Source Url */
            source_url: string;
            /** Target Column */
            target_column: string;
            /** Target Description */
            target_description: string;
            /**
             * Task
             * @enum {string}
             */
            task: "regression" | "binary_classification" | "multiclass_classification";
        };
        /** ExperimentCreateRequest */
        ExperimentCreateRequest: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Name */
            name: string;
            /** Tags */
            tags?: string[];
        };
        /** ExperimentResponse */
        ExperimentResponse: {
            /** Created At */
            created_at: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Experiment Id */
            experiment_id: string;
            /**
             * Is Ad Hoc
             * @default false
             */
            is_ad_hoc: boolean;
            /** Latest Run Id */
            latest_run_id?: string | null;
            /** Latest Status */
            latest_status?: ("queued" | "running" | "completed" | "failed" | "cancelled" | "interrupted") | null;
            /** Latest Updated At */
            latest_updated_at?: string | null;
            /** Name */
            name: string;
            /** Result Layout */
            result_layout?: string[];
            /**
             * Run Count
             * @default 0
             */
            run_count: number;
            /** Runs */
            runs?: components["schemas"]["RunResponse"][];
            /** Tags */
            tags?: string[];
        };
        /**
         * ExperimentSpec
         * @description Complete, reproducible specification accepted by API v1 and the CLI.
         */
        ExperimentSpec: {
            dataset?: components["schemas"]["DatasetSpec"];
            /**
             * Estimator
             * @default svm
             */
            estimator: string;
            evaluation?: components["schemas"]["EvaluationSpec"];
            /** Experiment Id */
            experiment_id?: string | null;
            /** Fixed Params */
            fixed_params?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Metric
             * @default roc_auc
             * @enum {string}
             */
            metric: "rmse" | "mae" | "r2" | "accuracy" | "roc_auc" | "pr_auc" | "log_loss" | "f1_macro";
            preprocessing?: components["schemas"]["PreprocessingSpec"];
            pso?: components["schemas"]["PsoSpec"];
            runtime?: components["schemas"]["RuntimeSpec"];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Search Space */
            search_space?: {
                [key: string]: components["schemas"]["ChoiceSearchParam"] | components["schemas"]["IntSearchParam"] | components["schemas"]["FloatSearchParam"];
            } | null;
            split?: components["schemas"]["SplitSpec"];
            /**
             * Strategy
             * @default random
             * @enum {string}
             */
            strategy: "pso" | "grid" | "random";
            /**
             * Task
             * @default binary_classification
             * @enum {string}
             */
            task: "regression" | "binary_classification" | "multiclass_classification";
        };
        /** FeatureSpec */
        FeatureSpec: {
            /** Categories */
            categories?: string[];
            /**
             * Kind
             * @default auto
             * @enum {string}
             */
            kind: "auto" | "numeric" | "nominal" | "ordinal";
        };
        /** FloatSearchParam */
        FloatSearchParam: {
            /** High */
            high: number;
            /** Low */
            low: number;
            /**
             * Precision
             * @default 4
             */
            precision: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "float" | "log_float";
        };
        /** FoldResponse */
        FoldResponse: {
            /** Cost */
            cost: number;
            /** Fold */
            fold: number;
            /** Metric */
            metric: number;
            /** Train Metric */
            train_metric: number;
            /** Train Metrics */
            train_metrics: {
                [key: string]: number | null;
            };
            /** Validation Metrics */
            validation_metrics: {
                [key: string]: number | null;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportanceItem */
        ImportanceItem: {
            /** Feature */
            feature: string;
            /** Importance */
            importance: number;
            /** Std */
            std?: number | null;
        };
        /** ImportanceResponse */
        ImportanceResponse: {
            /** Available */
            available: boolean;
            /** Items */
            items: components["schemas"]["ImportanceItem"][];
            /** Reason */
            reason?: string | null;
            /** Source */
            source?: string | null;
            /** Split */
            split?: string | null;
        };
        /** IntSearchParam */
        IntSearchParam: {
            /** High */
            high: number;
            /** Low */
            low: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "int";
        };
        JsonValue: unknown;
        /** MetadataResponse */
        MetadataResponse: {
            /** Estimators */
            estimators: {
                [key: string]: components["schemas"]["EstimatorResponse"];
            };
            /** Metrics */
            metrics: {
                [key: string]: components["schemas"]["MetricResponse"];
            };
            /** Tasks */
            tasks: {
                [key: string]: components["schemas"]["TaskResponse"];
            };
        };
        /** MetricResponse */
        MetricResponse: {
            /** Description */
            description: string;
            /** Label */
            label: string;
        };
        /** MulticlassRocResponse */
        MulticlassRocResponse: {
            /** Average */
            average: string;
            /** Curves */
            curves: components["schemas"]["RocResponse"][];
        };
        /** NumericSummaryResponse */
        NumericSummaryResponse: {
            /** Column */
            column: string | null;
            /** Count */
            count: number;
            /** Max */
            max: number | null;
            /** Mean */
            mean: number | null;
            /** Median */
            median: number | null;
            /** Min */
            min: number | null;
            /** Missing */
            missing: number;
            /**
             * Outliers Iqr
             * @default 0
             */
            outliers_iqr: number;
            /** Q25 */
            q25: number | null;
            /** Q75 */
            q75: number | null;
            /** Std */
            std: number | null;
        };
        /** OptimizationResultResponse */
        OptimizationResultResponse: {
            /** Artifacts */
            artifacts?: {
                [key: string]: string;
            };
            /** Best Cost */
            best_cost?: number | null;
            /** Best Metric */
            best_metric?: number | null;
            /** Best Params */
            best_params?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Best Position */
            best_position?: number[] | null;
            /** Duration */
            duration: number;
            /** Experiment Id */
            experiment_id?: string | null;
            /** Failures */
            failures?: string[];
            /**
             * Metric Name
             * @enum {string}
             */
            metric_name: "rmse" | "mae" | "r2" | "accuracy" | "roc_auc" | "pr_auc" | "log_loss" | "f1_macro";
            /** Optimizer State */
            optimizer_state?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Run Id */
            run_id?: string | null;
            /**
             * Strategy
             * @enum {string}
             */
            strategy: "pso" | "grid" | "random";
            /**
             * Task
             * @enum {string}
             */
            task: "regression" | "binary_classification" | "multiclass_classification";
            /** Trials */
            trials: components["schemas"]["TrialResponse"][];
        };
        /** PartitionResponse */
        PartitionResponse: {
            /** Percentage */
            percentage: number;
            /** Rows */
            rows: number;
            target: components["schemas"]["TargetResponse"];
        };
        /** PrecisionRecallResponse */
        PrecisionRecallResponse: {
            /** Auc */
            auc: number;
            /** Precision */
            precision: number[];
            /** Recall */
            recall: number[];
            /** Thresholds */
            thresholds: (number | null)[];
        };
        /** PredictionResponse */
        PredictionResponse: {
            /** Estimator */
            estimator: string;
            /** Feature Columns */
            feature_columns: string[];
            /**
             * Metric
             * @enum {string}
             */
            metric: "rmse" | "mae" | "r2" | "accuracy" | "roc_auc" | "pr_auc" | "log_loss" | "f1_macro";
            /** Preview Rows */
            preview_rows: components["schemas"]["PredictionRow"][];
            /** Row Count */
            row_count: number;
            /** Run Id */
            run_id: string;
            /**
             * Split
             * @enum {string}
             */
            split: "validation" | "train" | "test";
            /** Target Mapping */
            target_mapping?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /**
             * Task
             * @enum {string}
             */
            task: "regression" | "binary_classification" | "multiclass_classification";
        };
        /** PredictionRow */
        PredictionRow: {
            actual: components["schemas"]["JsonValue"];
            /** Features */
            features: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            predicted: components["schemas"]["JsonValue"];
            /** Probabilities */
            probabilities?: {
                [key: string]: number;
            } | null;
            /** Residual */
            residual?: number | null;
            /** Row Index */
            row_index: string | number;
            /** Score */
            score?: number | null;
        };
        /** PreprocessingSpec */
        PreprocessingSpec: {
            /**
             * Add Missing Indicators
             * @default false
             */
            add_missing_indicators: boolean;
            /**
             * Categorical Fill Value
             * @default Missing
             */
            categorical_fill_value: string;
            /**
             * Categorical Imputation
             * @default most_frequent
             * @enum {string}
             */
            categorical_imputation: "most_frequent" | "constant";
            /**
             * Encode Categorical
             * @default true
             */
            encode_categorical: boolean;
            /** Features */
            features?: {
                [key: string]: components["schemas"]["FeatureSpec"];
            };
            /** Ignored Columns */
            ignored_columns?: string[];
            /**
             * Numeric Fill Value
             * @default 0
             */
            numeric_fill_value: number;
            /**
             * Numeric Imputation
             * @default median
             * @enum {string}
             */
            numeric_imputation: "median" | "mean" | "most_frequent" | "constant";
            /**
             * Outlier Iqr Multiplier
             * @default 1.5
             */
            outlier_iqr_multiplier: number;
            /**
             * Outlier Lower Quantile
             * @default 0.01
             */
            outlier_lower_quantile: number;
            /**
             * Outlier Method
             * @default none
             * @enum {string}
             */
            outlier_method: "none" | "iqr" | "quantile";
            /**
             * Outlier Upper Quantile
             * @default 0.99
             */
            outlier_upper_quantile: number;
            /**
             * Scale Numeric
             * @default true
             */
            scale_numeric: boolean;
        };
        /**
         * ProgressPayload
         * @description Known progress fields are checked; recipes can add JSON-compatible details.
         */
        ProgressPayload: {
            /** Best Cost */
            best_cost?: number | null;
            /** Best Metric */
            best_metric?: number | null;
            /** Best Params */
            best_params?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Completed Fits */
            completed_fits?: number | null;
            /** Cost */
            cost?: number | null;
            /** Error */
            error?: string | null;
            /** Failed Fits */
            failed_fits?: number | null;
            /** Fit Id */
            fit_id?: number | null;
            /** Fold */
            fold?: number | null;
            /** Iteration */
            iteration?: number | null;
            /** Message */
            message?: string | null;
            /** Metric */
            metric?: number | ("rmse" | "mae" | "r2" | "accuracy" | "roc_auc" | "pr_auc" | "log_loss" | "f1_macro") | null;
            /** Params */
            params?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Particle Index */
            particle_index?: number | null;
            /** Phase */
            phase?: ("candidate" | "final_refit") | null;
            /** Planned Candidate Fits */
            planned_candidate_fits?: number | null;
            /** Planned Fits */
            planned_fits?: number | null;
            /** Planned Trials */
            planned_trials?: number | null;
            /** Reason */
            reason?: string | null;
            /** Strategy Slot */
            strategy_slot?: number | null;
            /** Total Fits */
            total_fits?: number | null;
            /** Total Folds */
            total_folds?: number | null;
            /** Trial Id */
            trial_id?: number | null;
            /** Worker Slot */
            worker_slot?: number | null;
        } & {
            [key: string]: components["schemas"]["JsonValue"];
        };
        /** PsoSpec */
        PsoSpec: {
            /**
             * C1
             * @default 1.49618
             */
            c1: number;
            /**
             * C2
             * @default 1.49618
             */
            c2: number;
            /**
             * Iterations
             * @default 10
             */
            iterations: number;
            /**
             * Particles
             * @default 5
             */
            particles: number;
            /**
             * Topology
             * @default global
             * @enum {string}
             */
            topology: "global" | "local";
            /**
             * W
             * @default 0.7298
             */
            w: number;
        };
        /** PythonRunSpec */
        PythonRunSpec: {
            /** Dataset */
            dataset: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Estimator */
            estimator: string;
            /** Fixed Params */
            fixed_params: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Metric
             * @enum {string}
             */
            metric: "rmse" | "mae" | "r2" | "accuracy" | "roc_auc" | "pr_auc" | "log_loss" | "f1_macro";
            /** Optimization */
            optimization: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Run Name */
            run_name?: string | null;
            /**
             * Schema Version
             * @constant
             */
            schema_version: 1;
            /** Search Space */
            search_space: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Source
             * @constant
             */
            source: "python";
            /**
             * Strategy
             * @enum {string}
             */
            strategy: "pso" | "grid" | "random";
            /**
             * Task
             * @enum {string}
             */
            task: "regression" | "binary_classification" | "multiclass_classification";
        };
        /** RegressionDiagnostics */
        RegressionDiagnostics: {
            /** Actual */
            actual: number[];
            /** Predicted */
            predicted: number[];
            /** Residuals */
            residuals: number[];
            /** Sampled */
            sampled: boolean;
        };
        /** ResultLayoutRequest */
        ResultLayoutRequest: {
            /** Tools */
            tools?: string[];
        };
        /** RocResponse */
        RocResponse: {
            /** Auc */
            auc: number;
            /** Fpr */
            fpr: number[];
            /** Label */
            label?: string | null;
            /** Thresholds */
            thresholds?: (number | null)[];
            /** Tpr */
            tpr: number[];
        };
        /** RunEventResponse */
        RunEventResponse: {
            payload: components["schemas"]["ProgressPayload"];
            /** Sequence Number */
            sequence_number: number;
            /** Timestamp */
            timestamp: string;
            /** Type */
            type: string;
        };
        /** RunHistoryResponse */
        RunHistoryResponse: {
            /** Events */
            events: components["schemas"]["RunEventResponse"][];
            /** Run Id */
            run_id: string;
        };
        /** RunResponse */
        RunResponse: {
            /** Artifacts */
            artifacts?: {
                [key: string]: string;
            };
            /** Attempts */
            attempts?: components["schemas"]["AttemptResponse"][];
            best?: components["schemas"]["BestResponse"] | null;
            /**
             * Cancel Requested
             * @default false
             */
            cancel_requested: boolean;
            /** Created At */
            created_at: string;
            /** Duration */
            duration?: number | null;
            /** Error */
            error?: string | null;
            /** Estimator */
            estimator?: string | null;
            /**
             * Event Count
             * @default 0
             */
            event_count: number;
            /**
             * Experiment Description
             * @default
             */
            experiment_description: string;
            /** Experiment Id */
            experiment_id: string;
            /** Experiment Name */
            experiment_name: string;
            /** Metric */
            metric?: ("rmse" | "mae" | "r2" | "accuracy" | "roc_auc" | "pr_auc" | "log_loss" | "f1_macro") | null;
            /**
             * N Failures
             * @default 0
             */
            n_failures: number;
            /**
             * N Trials
             * @default 0
             */
            n_trials: number;
            /** Parent Run Id */
            parent_run_id?: string | null;
            /** Queue Position */
            queue_position?: number | null;
            /** Request */
            request?: components["schemas"]["ExperimentSpec"] | components["schemas"]["PythonRunSpec"] | null;
            result?: components["schemas"]["OptimizationResultResponse"] | null;
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "completed" | "failed" | "cancelled" | "interrupted";
            /** Strategy */
            strategy?: ("pso" | "grid" | "random") | null;
            /** Task */
            task?: ("regression" | "binary_classification" | "multiclass_classification") | null;
            /** Updated At */
            updated_at: string;
        };
        /** RuntimeSpec */
        RuntimeSpec: {
            /** Early Stopping Rounds */
            early_stopping_rounds?: number | null;
            /** Max Trials */
            max_trials?: number | null;
            /** Timeout Seconds */
            timeout_seconds?: number | null;
            /**
             * Trial Workers
             * @default 1
             */
            trial_workers: number;
            /**
             * Verbose
             * @default 0
             */
            verbose: number;
        };
        /** SavedDatasetResponse */
        SavedDatasetResponse: {
            /** Created At */
            created_at: string;
            /** Dataset Id */
            dataset_id: string;
            /** Fingerprint */
            fingerprint: string;
            /** Name */
            name: string;
            profile: components["schemas"]["DatasetPreviewResponse"];
            /** Source Kind */
            source_kind: string;
            /** Source Path */
            source_path: string | null;
        };
        /** SplitResponse */
        SplitResponse: {
            /** Available */
            available: boolean;
            /** Error */
            error?: string | null;
            /**
             * Gap
             * @default 0
             */
            gap: number;
            /**
             * Method
             * @default random
             */
            method: string;
            /** Partitions */
            partitions?: {
                [key: string]: components["schemas"]["PartitionResponse"];
            };
            /** Random State */
            random_state?: number | null;
            /** Stratified */
            stratified?: boolean | null;
            /** Time Column */
            time_column?: string | null;
        };
        /** SplitSpec */
        SplitSpec: {
            /**
             * Gap
             * @default 0
             */
            gap: number;
            /**
             * Method
             * @default random
             * @enum {string}
             */
            method: "random" | "chronological";
            /**
             * Random State
             * @default 42
             */
            random_state: number | null;
            /**
             * Stratify
             * @default true
             */
            stratify: boolean;
            /**
             * Test Size
             * @default 0
             */
            test_size: number;
            /** Time Column */
            time_column?: string | null;
            /**
             * Validation Size
             * @default 0.2
             */
            validation_size: number;
        };
        /** TableSummaryResponse */
        TableSummaryResponse: {
            /** Categorical Columns */
            categorical_columns: number;
            /** Column Count */
            column_count: number;
            /** Duplicate Rows */
            duplicate_rows: number;
            /** Memory Bytes */
            memory_bytes: number;
            /** Numeric Columns */
            numeric_columns: number;
            /** Total Missing */
            total_missing: number;
        };
        /** TargetResponse */
        TargetResponse: {
            /** Count */
            count: number;
            /** Distribution */
            distribution?: components["schemas"]["DistributionRow"][] | null;
            /** Dtype */
            dtype: string;
            /** Examples */
            examples?: components["schemas"]["JsonValue"][];
            /** Missing */
            missing: number;
            /** Name */
            name: string;
            /** Statistics */
            statistics?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Unique */
            unique: number;
        };
        /** TaskResponse */
        TaskResponse: {
            /** Description */
            description: string;
            /** Label */
            label: string;
            /** Metrics */
            metrics: ("rmse" | "mae" | "r2" | "accuracy" | "roc_auc" | "pr_auc" | "log_loss" | "f1_macro")[];
        };
        /** TournamentRequest */
        TournamentRequest: {
            /** Runs */
            runs: components["schemas"]["ExperimentSpec"][];
        };
        /** TournamentResponse */
        TournamentResponse: {
            /** Experiment Id */
            experiment_id: string;
            /** Runs */
            runs: components["schemas"]["RunResponse"][];
        };
        /** TrialResponse */
        TrialResponse: {
            /** Cost */
            cost: number | null;
            /** Duration */
            duration: number;
            /** Error */
            error?: string | null;
            /** Failure Category */
            failure_category?: string | null;
            /** Fold Metrics */
            fold_metrics?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /** Iteration */
            iteration?: number | null;
            /** Metric */
            metric: number | null;
            /** Metric Std */
            metric_std?: number | null;
            /** Params */
            params: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Particle Index */
            particle_index?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "completed" | "failed";
            /** Strategy Slot */
            strategy_slot?: number | null;
            /** Train Metric */
            train_metric: number | null;
            /** Train Metrics */
            train_metrics?: {
                [key: string]: number | null;
            };
            /** Trial Id */
            trial_id: number;
            /** Validation Metrics */
            validation_metrics?: {
                [key: string]: number | null;
            };
            /** Worker Slot */
            worker_slot?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationResponse */
        ValidationResponse: {
            /** Errors */
            errors: {
                [key: string]: string[];
            };
            /** Stage */
            stage?: string | null;
            /** Valid */
            valid: boolean;
        };
        /** WorkflowValidationRequest */
        WorkflowValidationRequest: {
            request: components["schemas"]["ExperimentSpec"];
            /**
             * Stage
             * @default full
             * @enum {string}
             */
            stage: "data" | "model" | "search" | "full";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    list_saved_datasets_api_v1_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedDatasetResponse"][];
                };
            };
        };
    };
    create_saved_dataset_api_v1_datasets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatasetCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedDatasetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    datasets_examples_api_v1_datasets_examples_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExampleDatasetResponse"][];
                };
            };
        };
    };
    datasets_inspect_api_v1_datasets_inspect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatasetInspectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    datasets_preview_api_v1_datasets_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CsvPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    estimators_api_v1_estimators_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetadataResponse"];
                };
            };
        };
    };
    list_experiments_api_v1_experiments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentResponse"][];
                };
            };
        };
    };
    create_experiment_api_v1_experiments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_experiment_api_v1_experiments__experiment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_result_layout_api_v1_experiments__experiment_id__result_layout_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResultLayoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_tournament_api_v1_experiments__experiment_id__tournament_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TournamentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TournamentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"][];
                };
            };
        };
    };
    create_run_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentSpec"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_run_api_v1_runs_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentSpec"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_api_v1_runs__run_id__analysis_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifacts_api_v1_runs__run_id__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_v1_runs__run_id__events_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: {
                "Last-Event-ID"?: number | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_run_api_v1_runs__run_id__exports__kind__get: {
        parameters: {
            query?: {
                split?: ("validation" | "train" | "test") | null;
            };
            header?: never;
            path: {
                run_id: string;
                kind: "spec" | "result" | "analysis" | "events" | "predictions" | "metrics" | "manifest" | "model" | "selection_model" | "preprocessor" | "environment" | "split_indices" | "log";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calculate_feature_importance_api_v1_runs__run_id__feature_importance_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_api_v1_runs__run_id__history_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_predictions_api_v1_runs__run_id__predictions_get: {
        parameters: {
            query?: {
                split?: "validation" | "train" | "test";
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_result_api_v1_runs__run_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_run_api_v1_runs__run_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_workflow_api_v1_workflow_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowValidationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
